### ISSUE TITLE
Incompatible plugin

### ISSUE THREAD

**Issue by danoetz** [PureAway/CommonTools#1]
![Screenshot 2023-01-20 at 06 31 40](https://user-images.githubusercontent.com/4177312/213585277-272f39e7-ab26-4192-8a41-121c867ba4fb.png)

**Comment by PureAway** [comment]
@danoetz uninstall old version and install new version of plugins, the newest version of CommonTools is 1.3.0 which supported AndroidStudio unitl build version 221.6008.13.
